name: dermdetect
description: "Aplicacion para detectar enfermedades de la piel, usando inteligencia artificial."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.6
  tflite_flutter: ^0.10.1
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
